### ISSUE TITLE
json_to_devices.py erroring on current device dump

### ISSUE THREAD

**Issue by DavidGriffith** [DavidGriffith/minipro-import-test#170]
In GitLab by @Kreeblah on Mar 31, 2020, 23:54

I'm attempting to dump the current version (10.06) of the device list supported by XGecu's official software for the TL866II Plus, but I keep getting an error when I attempt to run the Python script.

I'm going about doing this by compiling the dumpic applications on Windows and using dump-infoic2plus-dll.exe to process the data from the DLL and redirecting it to a JSON file:

dump-infoic2plus-dll.exe C:\Xgpro\InfoIC2Plus.dll > test.json

From there, I'm attempting to feed it into json_to_devices.py, but I keep getting this error:

Traceback (most recent call last):
  File "./json_to_devices.py", line 1092, in <module>
    main()
  File "./json_to_devices.py", line 1058, in main
    json_database = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 262916 column 36 (char 6942303)

It doesn't seem to matter whether I use Python 2.7 or 3.8, or whether I run the Python script on Windows, Linux, or macOS.  It always has an invalid control character at line 262916, column 36 of the JSON file.  The only differences are that it changes from a ValueError in 2.7 to a JSON decoder error in 3.8, and the char position changes to 6679388.  The line number and column remain the same, though.

Any ideas how I can do this properly?

**Comment by DavidGriffith** [comment]
In GitLab by @radiomanV on Apr 2, 2020, 02:14

Please don't use `dump-infoic2plus-dll.exe`. It is outdated and it doesn't produce a valid dump for the current minipro implementation. There's a graphical infoic2plus.dll dumper on my github repo (https://github.com/radiomanV/TL866) which was used to produce current `infoic2plus_devices.h` header but it was not tested on the current xgpro .dll.   
Also, there are some obscure things like manually edited entries for some chips and some firmware incompatibilities workarounds.

**Comment by DavidGriffith** [comment]
In GitLab by @Kreeblah on Apr 2, 2020, 17:15

Oh, that's good information.  Thank you!

Regarding the manually-edited entries, is there a list of those by any chance?  Alternately, do you know offhand what version of the DLL was used as the basis for the current header file that I could compare against it?

**Comment by DavidGriffith** [comment]
In GitLab by @radiomanV on Apr 3, 2020, 06:11

Yes there is. All Pic controllers and all entries from the `infoic2plus_custom.h` header. There are two .csv files (one for atmel and one for microchip controllers) in my infoic dumper. These two files are manualy edited by me for each supported processor. When the dump process starts all the missing info (chip id and chip type) are taken from these two files.    

The used dll version is in the infoic2plus_devices.h (`//Patched V8.51 database`) see !130 merge request and my !141.
