### ISSUE TITLE
Segmentation fault during auto-detect

### ISSUE THREAD

**Issue by DavidGriffith** [DavidGriffith/minipro-import-test#285]
In GitLab by @mole99 on Mar 4, 2023, 11:00

I am using Debian Bookworm and have compiled minipro from source.
When I try to autodetect a flash chip, minipro crashes. It does not matter if a chip is present

I have updated the firmware of the TL866II+ to the latest version.

```
./minipro -a 8
Found TL866II+ 04.2.132 (0x284)
Speicherzugriffsfehler
```

(Speicherzugriffsfehler means Segmentation fault in German)

Let me know if I can provide more information.

**Comment by DavidGriffith** [comment]
In GitLab by @maaarghk on Mar 22, 2023, 18:10

Same:

```
446		if (handle->device->flags.custom_protocol) {
#0  tl866a_spi_autodetect (handle=0x55e1939e22a0, type=0 '\000', device_id=0x7fffc98dfb10) at tl866a.c:446
#1  0x000055e1929dbe21 in minipro_spi_autodetect (handle=0x55e1939e22a0, type=0 '\000', device_id=0x7fffc98dfb10) at minipro.c:436
#2  0x000055e1929e6eed in spi_autodetect_and_exit (package_type=8 '\b', cmdopts=0x7fffc98dfce0) at main.c:638
#3  0x000055e1929e76de in parse_cmdline (argc=3, argv=0x7fffc98dfe48, cmdopts=0x7fffc98dfce0) at main.c:892
#4  0x000055e1929ee241 in main (argc=3, argv=0x7fffc98dfe48) at main.c:2838
```

**Comment by DavidGriffith** [comment]
In GitLab by @vitalinya on Jul 17, 2023, 06:30

As workaround try to downgrade programmer fw to 123 and minipro to 0.5.

https://github.com/mike-pittelko/TL866IIPlus-Firmware
